Repository NextPage-BookJuk/BookJuk, pull requests merged in 2025-08, with the labels that each got.

#9 feat: #5 공통 에러코드 처리 작성
  build.gradle
  src/main/java/com/bookjuk/exception/CustomException.java
  src/main/java/com/bookjuk/exception/ErrorCode.java
  src/main/java/com/bookjuk/exception/GlobalExceptionHandler.java
  src/main/java/com/bookjuk/exception/dto/ErrorResponse.java
  src/main/java/com/bookjuk/support/DummyController.java
  src/test/java/com/bookjuk/exception/GlobalExceptionHandlerTest.java
Labels: enhancement

#12 feat: #11 templates 내 단일 HTML에서 JS/CSS 분리(정적 리소스 구조화)
  src/main/java/com/bookjuk/BookJukApplication.java
  src/main/java/com/bookjuk/controller/PageTestController.java
  src/main/resources/static/.gitkeep
  src/main/resources/static/css/auth.css
  src/main/resources/static/css/board-detail.css
  src/main/resources/static/css/create-meeting.css
  src/main/resources/static/css/edit-profile.css
  src/main/resources/static/css/meeting-detail.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/board-detail.js
  src/main/resources/static/js/create-meeting.js
  src/main/resources/static/js/edit-profile.js
  src/main/resources/static/js/meeting-detail.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/.gitkeep
  src/main/resources/templates/auth.html
  src/main/resources/templates/board-detail.html
  src/main/resources/templates/create-meeting.html
  src/main/resources/templates/edit-profile.html
  src/main/resources/templates/meeting-detail.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#22 feat: #13 모임 생성 entity 및 dto 정의
  src/main/java/com/bookjuk/domain/meeting/Meeting.java
  src/main/java/com/bookjuk/domain/meeting/MeetingStatus.java
  src/main/java/com/bookjuk/domain/user/User.java
  src/main/java/com/bookjuk/dto/meeting/MeetingCreateRequest.java
Labels: enhancement

#27 feat: #26 review(좋아요) entity, dto, ReviewRepository 구현
  src/main/java/com/bookjuk/controller/ReviewController.java
  src/main/java/com/bookjuk/domain/review/MeetingReview.java
  src/main/java/com/bookjuk/dto/review/ReviewRequest.java
  src/main/java/com/bookjuk/dto/review/ReviewResponse.java
  src/main/java/com/bookjuk/repository/review/MeetingReviewRepository.java
  src/main/java/com/bookjuk/service/ReviewService.java
Labels: enhancement

#34 feat: #33 API 응답 DTO 구현
  src/main/java/com/bookjuk/dto/common/ApiResponse.java
Labels: enhancement

#37 feat : User 엔터티 작성 및 DTO 클래스 정의 / Jwt 관련 속성과 클래스 추가
  .gitignore
  build.gradle
  src/main/java/com/bookjuk/config/SecurityConfig.java
  src/main/java/com/bookjuk/domain/user/User.java
  src/main/java/com/bookjuk/dto/user/UserLoginRequest.java
  src/main/java/com/bookjuk/dto/user/UserResponse.java
  src/main/java/com/bookjuk/dto/user/UserSignupRequest.java
  src/main/java/com/bookjuk/dto/user/request/UserLoginRequest.java
  src/main/java/com/bookjuk/dto/user/request/UserSignupRequest.java
  src/main/java/com/bookjuk/dto/user/response/AuthResponse.java
  src/main/java/com/bookjuk/dto/user/response/EmailCheckResponse.java
  src/main/java/com/bookjuk/dto/user/response/UserResponse.java
  src/main/java/com/bookjuk/jwt/JwtProperties.java
  src/main/java/com/bookjuk/jwt/JwtProvider.java
  src/main/resources/application.yml
  src/main/resources/static/images/defaultProfile.png
  src/test/java/com/bookjuk/repository/meeting/MeetingRepositoryTest.java
Labels: enhancement

#39 feat: 데이터 레이어 설계(엔티티/레포지토리)
  build.gradle
  src/main/java/com/bookjuk/domain/board/Comment.java
  src/main/java/com/bookjuk/domain/board/Post.java
  src/main/java/com/bookjuk/repository/board/CommentRepository.java
  src/main/java/com/bookjuk/repository/board/PostRepository.java
  src/main/java/com/bookjuk/repository/participant/MeetingParticipantRepository.java
  src/test/java/com/bookjuk/repository/meeting/MeetingRepositoryTest.java
Labels: enhancement

#69 feat: 모임 생성 시 로그인 상태 및 이미지 검증 로직 추가 #66
  src/main/java/com/bookjuk/config/SecurityConfig.java
  src/main/java/com/bookjuk/controller/MeetingController.java
  src/main/java/com/bookjuk/repository/participant/MeetingParticipantRepository.java
  src/main/java/com/bookjuk/service/MeetingService.java
  src/main/java/com/bookjuk/service/ReviewService.java
  src/main/resources/static/js/create-meeting.js
Labels: enhancement

#70 feat: 마이페이지 비즈니스 로직 구현
  src/main/java/com/bookjuk/dto/mypage/MyPageResponse.java
  src/main/java/com/bookjuk/dto/mypage/StaticsInfoDto.java
  src/main/java/com/bookjuk/dto/review/ReviewResponse.java
  src/main/java/com/bookjuk/repository/participant/MeetingParticipantCustom.java
  src/main/java/com/bookjuk/repository/participant/MeetingParticipantRepositoryImpl.java
  src/main/java/com/bookjuk/repository/review/MeetingReviewCustom.java
  src/main/java/com/bookjuk/repository/review/MeetingReviewRepositoryImpl.java
  src/main/java/com/bookjuk/service/MyPageService.java
Labels: enhancement

#73 [feat] : 로그인/회원가입 UI 및 인증 스크립트 구현 / [test] : 회원가입 및 로그인 기능 End-to-End 테스트
  src/main/java/com/bookjuk/config/SecurityConfig.java
  src/main/java/com/bookjuk/controller/PageTestController.java
  src/main/java/com/bookjuk/routes/PageController.java
  src/main/resources/static/css/auth.css
  src/main/resources/static/js/auth.js
  src/main/resources/templates/auth.html
Labels: documentation, enhancement

#109 Fix: board-detail.html 닫혀있지 않는 이슈 확인 후 수정
  src/main/resources/templates/board-detail.html
Labels: bug

#113 fix: 마이페이지, 프로필 수정 페이지 헤더 변경, 디폴트 이미지 설정
  src/main/java/com/bookjuk/controller/ReviewController.java
  src/main/java/com/bookjuk/service/MyPageService.java
  src/main/resources/static/css/edit-profile.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/edit-profile.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/edit-profile.html
  src/main/resources/templates/mypage.html
Labels: bug

#115 refacotr: 마이페이지 모임 정보 리스트에 페이징 기능 추가
  src/main/java/com/bookjuk/controller/MyPageController.java
  src/main/java/com/bookjuk/dto/mypage/MyPageResponse.java
  src/main/java/com/bookjuk/dto/mypage/StaticsInfoDto.java
  src/main/java/com/bookjuk/repository/participant/MeetingParticipantCustom.java
  src/main/java/com/bookjuk/repository/participant/MeetingParticipantRepositoryImpl.java
  src/main/java/com/bookjuk/service/MyPageService.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
Labels: wontfix
